[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
capstone = { version = "0.13" }
memmap2   = "0.9"
goblin    = "0.8"
byteorder = "1.4"
anyhow    = "1.0"
thiserror = "1.0"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
